# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
  title: Guanxu Chen
  params:
    description: Ph.D. student at Shanghai Jiao Tong University and Shanghai AI Laboratory.
